# fetch data from api

In [109]:
import pandas as pd
import requests as re

In [214]:
url = f"https://api.themoviedb.org/3/movie/top_rated"
params = {
        "api_key": "183099375f1634a4a8aa383f04afae2c",
        "language": "en-US",
        "page": i
    }
res = requests.get(url,params=params, timeout=10)
data = res.json()

In [215]:
data

{'page': 500,
 'results': [{'adult': False,
   'backdrop_path': '/lQgsnfkTGA8RXaoBEQ4oMtbJhIB.jpg',
   'genre_ids': [18, 14, 9648],
   'id': 9697,
   'title': 'Lady in the Water',
   'original_language': 'en',
   'original_title': 'Lady in the Water',
   'overview': 'Apartment building superintendent Cleveland Heep rescues what he thinks is a young woman from the pool he maintains. When he discovers that she is actually a character from a bedtime story who is trying to make the journey back to her home, he works with his tenants to protect his new friend from the creatures that are determined to keep her in our world.',
   'popularity': 2.3651,
   'poster_path': '/ddNmoSy1Jd3PBF5XDZvrrBIfrja.jpg',
   'release_date': '2006-07-19',
   'softcore': False,
   'video': False,
   'vote_average': 5.564,
   'vote_count': 1486},
  {'adult': False,
   'backdrop_path': '/4BXLVLRwHxtydcUIhxphPVirJX5.jpg',
   'genre_ids': [12, 14, 27, 35],
   'id': 74461,
   'title': 'Knights of Badassdom',
   'original_language': 'en',
   'original_title': 'Knights of Badassdom',
   'overview': 'Three best friends and dedicated roleplayers take to the woods to reenact a dungeons and dragons-like scenario as a live action role-playing game. Trouble arises when a prop spellbook purchased from the internet ends up being a genuine grimoire and they unwittingly conjure up a blood-lusting succubus from hell.',
   'popularity': 1.2632,
   'poster_path': '/7hxpi2Y7JNGHmETL2VAPONhvHGZ.jpg',
   'release_date': '2014-01-21',
   'softcore': False,
   'video': False,
   'vote_average': 5.563,
   'vote_count': 444},
  {'adult': False,
   'backdrop_path': '/x2cbN0s2RFN4hwsTZpegcWxZ0wH.jpg',
   'genre_ids': [27, 9648],
   'id': 26688,
   'title': 'Sorority Row',
   'original_language': 'en',
   'original_title': 'Sorority Row',
   'overview': 'When five sorority girls inadvertently cause the murder of one of their sisters in a prank gone wrong, they agree to keep the matter to themselves and never speak of it again, so they can get on with their lives. This proves easier said than done, when after graduation a mysterious killer goes after the five of them and anyone who knows their secret.',
   'popularity': 2.8537,
   'poster_path': '/voIQd9TDplumz9wInHwj6bRyHnu.jpg',
   'release_date': '2009-09-09',
   'softcore': False,
   'video': False,
   'vote_average': 5.6,
   'vote_count': 615},
  {'adult': False,
   'backdrop_path': '/wN5EnpDUmrusp73qD0fZsOXtqVh.jpg',
   'genre_ids': [10751, 35],
   'id': 10438,
   'title': "Beethoven's 2nd",
   'original_language': 'en',
   'original_title': "Beethoven's 2nd",
   'overview': "Beethoven is back -- and this time, he has a whole brood with him now that he's met his canine match, Missy, and fathered a family. The only problem is that Missy's owner, Regina, wants to sell the puppies and tear the clan apart. It's up to Beethoven and the Newton kids to save the day and keep everyone together.",
   'popularity': 1.8437,
   'poster_path': '/biH5hW1BRfEr13oCizuAzpdBf2l.jpg',
   'release_date': '1993-12-14',
   'softcore': False,
   'video': False,
   'vote_average': 5.6,
   'vote_count': 1060},
  {'adult': False,
   'backdrop_path': '/750Uayj0Bww4QfqMUJCymW3EJkC.jpg',
   'genre_ids': [12, 10751],
   'id': 36355,
   'title': 'Flipper',
   'original_language': 'en',
   'original_title': 'Flipper',
   'overview': 'Sandy Ricks is sent by his mom to Coral Key, a rustic island in the Florida keys, to spend the summer with his uncle Porter Ricks. Sandy dislikes everything about his new environment until a new friend comes into his life, a dolphin named Flipper, that brings uncle and nephew together and leads Sandy on the summer adventure of a lifetime.',
   'popularity': 1.9657,
   'poster_path': '/c3KEzecZ5oE6CpSrWX6wCLrBJbf.jpg',
   'release_date': '1996-05-17',
   'softcore': False,
   'video': False,
   'vote_average': 5.6,
   'vote_count': 346},
  {'adult': False,
   'backdrop_path': '/uOzlRVpPjZ3GHPggc2mk8ma2TI8.jpg',
   'genre_ids': [35, 10749, 18],
   'id': 11523,
   'title': 'View from the Top',
   'original_language': 'en',
   'original_title': 'View from the Top',
   'overview': "No one thought Donna would go very far. But when she sets her sights on becoming a first-class international flight attendant, Donna throws caution to the wind and takes off in pursuit of her dream. The ride is anything but smooth, however, and Donna's laugh-packed journey of a lifetime is rocked by more turbulence than she bargained for.",
   'popularity': 1.8783,
   'poster_path': '/q8oHvYoFICQpTWjC15ZMwQr5Sox.jpg',
   'release_date': '2003-03-21',
   'softcore': False,
   'video': False,
   'vote_average': 5.6,
   'vote_count': 604},
  {'adult': False,
   'backdrop_path': '/v018UdfS3WDGGfUyWlk4byUWzon.jpg',
   'genre_ids': [35, 27],
   'id': 255798,
   'title': 'Burying the Ex',
   'original_language': 'en',
   'original_title': 'Burying the Ex',
   'overview': 'Before horror enthusiast Max can break things off with his girlfriend Evelyn she dies in a bus accident. In time, Max meets another woman only to have Evelyn resurface as a zombie ready to resume their relationship.',
   'popularity': 1.3942,
   'poster_path': '/kVE5JElUQVLL95GZCiQhLSTTA6I.jpg',
   'release_date': '2014-09-04',
   'softcore': False,
   'video': False,
   'vote_average': 5.561,
   'vote_count': 520},
  {'adult': False,
   'backdrop_path': '/5wxjd6D6jX8XlhQRw3rUiwl4HwK.jpg',
   'genre_ids': [28, 878, 53],
   'id': 122857,
   'title': 'Universal Soldier: Day of Reckoning',
   'original_language': 'en',
   'original_title': 'Universal Soldier: Day of Reckoning',
   'overview': 'After his wife and daughter are murdered in a home invasion, a widower named John now finds himself up against an army of Universal Soldiers in relentless pursuit, led by a mysterious leader who promises to set UniSols free from their conditioning.',
   'popularity': 2.0852,
   'poster_path': '/4pefZa0U5h0avmdvRwWB4xjMFl6.jpg',
   'release_date': '2012-10-04',
   'softcore': False,
   'video': False,
   'vote_average': 5.561,
   'vote_count': 485},
  {'adult': False,
   'backdrop_path': '/7hN4MAlz386PpEwzTNcj88F1JCw.jpg',
   'genre_ids': [27, 53],
   'id': 10984,
   'title': 'Valentine',
   'original_language': 'en',
   'original_title': 'Valentine',
   'overview': "Four friends start to receive morbid Valentine cards and realise they are being stalked by someone they had spurned 13 years ago. A masked killer is on the loose and Valentine's day is soon approaching.",
   'popularity': 1.807,
   'poster_path': '/jMtWV4FixMGTgUjbr9NFVEANGYQ.jpg',
   'release_date': '2001-02-02',
   'softcore': False,
   'video': False,
   'vote_average': 5.561,
   'vote_count': 604},
  {'adult': False,
   'backdrop_path': '/4fU2ddunguMjxWK0oWdUfKES9Qo.jpg',
   'genre_ids': [28, 35],
   'id': 5851,
   'title': 'Showtime',
   'original_language': 'en',
   'original_title': 'Showtime',
   'overview': 'A spoof of buddy cop movies where two very different cops are forced to team up on a new reality based T.V. cop show.',
   'popularity': 1.7699,
   'poster_path': '/8sIooUxXZo2blCVuAYbL2wkdUfD.jpg',
   'release_date': '2002-03-14',
   'softcore': False,
   'video': False,
   'vote_average': 5.561,
   'vote_count': 1077},
  {'adult': False,
   'backdrop_path': '/uzAkYdMm9NKSateeKSOh8dEf9JE.jpg',
   'genre_ids': [27],
   'id': 301846,
   'title': 'Howl',
   'original_language': 'en',
   'original_title': 'Howl',
   'overview': 'When passengers on a train are attacked by a creature, they must band together in order to survive until morning.',
   'popularity': 2.5667,
   'poster_path': '/XcwP3VGTRVHjc4doNP8w1fdOJ7.jpg',
   'release_date': '2015-10-01',
   'softcore': False,
   'video': False,
   'vote_average': 5.56,
   'vote_count': 563},
  {'adult': False,
   'backdrop_path': '/3m0j3hCS8kMAaP9El6Vy5Lqnyft.jpg',
   'genre_ids': [878, 27, 53],
   'id': 1125510,
   'title': 'The Platform 2',
   'original_language': 'es',
   'original_title': 'El hoyo 2',
   'overview': 'After a mysterious leader imposes his law in a brutal system of vertical cells, a new arrival battles against a dubious food distribution method.',
   'popularity': 4.3472,
   'poster_path': '/tvIpBg12IIA5Dr9Sjn38ygS1vQp.jpg',
   'release_date': '2024-09-27',
   'softcore': False,
   'video': False,
   'vote_average': 5.559,
   'vote_count': 1425},
  {'adult': False,
   'backdrop_path': '/hzBLtqQs1jdclPu71xlNcyiXOBD.jpg',
   'genre_ids': [35, 10770],
   'id': 15671,
   'title': 'Picture This',
   'original_language': 'en',
   'original_title': 'Picture This',
   'overview': "Bookish and unpopular Mandy finds her luck finally changing when Drew, the school hottie, invites her to the year's biggest party. But with being grounded and Drew's ex-girlfriend bent on thwarting her, Mandy may be destined to remain a geek. Can a little ingenuity and some help from her friends save the day?",
   'popularity': 1.0318,
   'poster_path': '/f0Mc2OzARakkTmnm8sihEQSoVaI.jpg',
   'release_date': '2008-07-13',
   'softcore': False,
   'video': False,
   'vote_average': 5.6,
   'vote_count': 324},
  {'adult': False,
   'backdrop_path': '/1BEuoA7UpCF51WpiIZ7rypAhxfs.jpg',
   'genre_ids': [10751, 28, 12, 35, 14, 878],
   'id': 6589,
   'title': 'Underdog',
   'original_language': 'en',
   'original_title': 'Underdog',
   'overview': 'A lab accident gives a beagle named Shoeshine some serious superpowers -- a secret that the dog eventually shares with the young boy who becomes his owner and friend.',
   'popularity': 3.2424,
   'poster_path': '/q5yoIlzQ3m7b3a0zLCf3NjsOvB8.jpg',
   'release_date': '2007-08-03',
   'softcore': False,
   'video': False,
   'vote_average': 5.558,
   'vote_count': 762},
  {'adult': False,
   'backdrop_path': '/2KX79ljurDq6bBXcyoQLROVxkU8.jpg',
   'genre_ids': [53, 12, 28],
   'id': 602654,
   'title': 'Horizon Line',
   'original_language': 'en',
   'original_title': 'Horizon Line',
   'overview': 'A couple flying on a small plane to attend a tropical island wedding must fight for their lives after their pilot suffers a heart attack.',
   'popularity': 2.2966,
   'poster_path': '/vWGkIHeCLw9wWvPXnPTOM9d5GiK.jpg',
   'release_date': '2020-10-29',
   'softcore': False,
   'video': False,
   'vote_average': 5.557,
   'vote_count': 419},
  {'adult': False,
   'backdrop_path': '/uKrfP5T5EwlR5RPGDEbFzDSaljJ.jpg',
   'genre_ids': [35, 10749],
   'id': 19899,
   'title': 'Couples Retreat',
   'original_language': 'en',
   'original_title': 'Couples Retreat',
   'overview': 'Four couples, all friends, descend on a tropical island resort. Though one husband and wife are there to work on their marriage, the others just want to enjoy some fun in the sun. They soon find, however, that paradise comes at a price: Participation in couples therapy sessions is mandatory. What started out as a cut-rate vacation turns into an examination of the common problems many face.',
   'popularity': 3.384,
   'poster_path': '/igXVSRZsNX3TZsKrQqSyEJvzHRF.jpg',
   'release_date': '2009-09-19',
   'softcore': False,
   'video': False,
   'vote_average': 5.557,
   'vote_count': 2092},
  {'adult': False,
   'backdrop_path': '/p2h886S7r4znUYvp1ELOTq7jqUZ.jpg',
   'genre_ids': [35, 10749],
   'id': 49012,
   'title': 'Arthur',
   'original_language': 'en',
   'original_title': 'Arthur',
   'overview': "A drunken playboy stands to lose a wealthy inheritance when he falls for a woman that his family doesn't like.",
   'popularity': 2.9198,
   'poster_path': '/foUTAJurvnbUoIUbnuUk5dyHx7M.jpg',
   'release_date': '2011-04-08',
   'softcore': False,
   'video': False,
   'vote_average': 5.556,
   'vote_count': 798},
  {'adult': False,
   'backdrop_path': '/k6OumxPkrJ4KuirkOU0Gw1KhzdM.jpg',
   'genre_ids': [27, 53],
   'id': 364116,
   'title': 'The Other Side of the Door',
   'original_language': 'en',
   'original_title': 'The Other Side of the Door',
   'overview': 'Grieving over the loss of her son, a mother struggles with her feelings for her daughter and her husband. She seeks out a ritual that allows her say goodbye to her dead child, opening the veil between the world of the dead and the living. Her daughter becomes the focus of terror. She must now protect against the evil that was once her beloved son.',
   'popularity': 2.026,
   'poster_path': '/z5HubVaGLp1EXQbEXhg6hbEYee9.jpg',
   'release_date': '2016-02-25',
   'softcore': False,
   'video': False,
   'vote_average': 5.551,
   'vote_count': 895},
  {'adult': False,
   'backdrop_path': '/oX29bzX5KNNPGg2bUZnZB7oOpUL.jpg',
   'genre_ids': [35, 10749],
   'id': 174316,
   'title': 'A Case of You',
   'original_language': 'en',
   'original_title': 'A Case of You',
   'overview': 'Young writer Sam has a crush on Birdie, the cute and quirky barista at his local coffee shop. When his conventional attempts to woo her crash and burn, he takes his efforts online, creating an Internet profile embellished with all of the details that would make him Birdie’s dream guy. When the harebrained scheme is a surprise success and Birdie falls for his exaggerated alter ego, Sam must keep up the act or lose his dream girl forever.',
   'popularity': 1.1291,
   'poster_path': '/qP6X7K5BWtQv28leIpxJNmq1deB.jpg',
   'release_date': '2013-11-06',
   'softcore': False,
   'video': False,
   'vote_average': 5.555,
   'vote_count': 320},
  {'adult': False,
   'backdrop_path': '/4VNpU3Hjjslfd5CY0Ywr7zSgObM.jpg',
   'genre_ids': [878, 18, 12, 80, 28],
   'id': 582607,
   'title': 'See You Yesterday',
   'original_language': 'en',
   'original_title': 'See You Yesterday',
   'overview': 'As two teen prodigies try to master the art of time travel, a tragic police shooting sends them on a series of dangerous trips to the past.',
   'popularity': 0.7765,
   'poster_path': '/d5uA1DdiWK5KH5yzyMfh1X3uXie.jpg',
   'release_date': '2019-05-03',
   'softcore': False,
   'video': False,
   'vote_average': 5.6,
   'vote_count': 563}],
 'total_pages': 546,
 'total_results': 10910}

In [ ]:

frames = []   # list to store each page’s DataFram

for i in range(1, 501):
    url = f"https://api.themoviedb.org/3/movie/top_rated"
    params = {
        "api_key": "183099375f1634a4a8aa383f04afae2c",
        "language": "en-US",
        "page": i
    }
    res = requests.get(url,params=params, timeout=10)
    data = res.json()

    if "results" in data:
        temp_df = pd.DataFrame(data["results"])[[
            "id", "adult", "original_title", "release_date",
            "vote_count", "popularity", "overview"
        ]]
        frames.append(temp_df)  
    else:
        print(f"⚠️ No results on page {i}: {data}")


df = pd.concat(frames, ignore_index=True)

print("Total movies collected:", len(df))
print(df.head())

In [145]:
df

,id,adult,original_title,release_date,vote_count,popularity,overview
0,1007757,False,Swapped,2026-05-01,1632,210.0350,"A small woodland creature and a majestic bird,..."
1,278,False,The Shawshank Redemption,1994-09-23,30519,82.6474,Imprisoned in the 1940s for the double murder ...
2,238,False,The Godfather,1972-03-14,23007,43.0209,"Spanning the years 1945 to 1955, a chronicle o..."
3,687163,False,Project Hail Mary,2026-03-15,4802,231.4921,Science teacher Ryland Grace wakes up on a spa...
4,240,False,The Godfather Part II,1974-12-20,13950,29.8389,In the continuing saga of the Corleone crime f...
...,...,...,...,...,...,...,...
9995,49012,False,Arthur,2011-04-08,798,2.9198,A drunken playboy stands to lose a wealthy inh...
9996,364116,False,The Other Side of the Door,2016-02-25,895,2.0260,"Grieving over the loss of her son, a mother st..."
9997,174316,False,A Case of You,2013-11-06,320,1.1291,"Young writer Sam has a crush on Birdie, the cu..."
9998,582607,False,See You Yesterday,2019-05-03,563,0.7765,As two teen prodigies try to master the art of...
9999,369776,False,Les Tuche 2 : Le Rêve américain,2016-02-03,1020,0.7828,"Les Tuche, a modest french family, change his ..."

In [123]:
df.to_csv('movies_api.csv')

Empty DataFrame
Columns: []
Index: []

In [216]:
import requests

url = "https://ebay-average-selling-price.p.rapidapi.com/findCompletedItems"

headers = {
    "x-rapidapi-key": "50677ba5d5msh5e6bb409c408a3dp1292a7jsn8e64a441ed55",
    "x-rapidapi-host": "ebay-average-selling-price.p.rapidapi.com",
    "Content-Type": "application/json"
}

payload = {
    "keywords": "iPhone",
    "excluded_keywords": "locked cracked case box read LCD",
    "max_search_results": "240",
    "category_id": "9355",
    "remove_outliers": "true",
    "site_id": "0",
    "aspects": [
        {"name": "Model", "value": "Apple iPhone X"},
        {"name": "LH_ItemCondition", "value": "3000"},
        {"name": "Network", "value": "Unlocked"},
        {"name": "Storage Capacity", "value": "64 GB"}
    ]
}

response = requests.post(url, headers=headers, json=payload)

# print(response.status_code)
data = response.json()

In [217]:
products = data['products']

df = pd.DataFrame(products)

In [226]:
df

,title,sale_price,currency,condition,buying_format,date_sold,image_url,shipping_price,link,item_id
0,Apple iPhone X 64GB (Unlocked) A1865 Silver Sm...,84.95,$,Apple iPhone X,Buy It Now,"Jun 8, 2026",https://i.ebayimg.com/images/g/8gsAAeSwCKtqImj...,0.00,https://www.ebay.com/itm/147352659891?_skw=iPh...,147352659891
1,Apple iPhone X - 64GB - Silverish White Untested,110.60,$,Apple iPhone X,Buy It Now,"Jun 8, 2026",https://i.ebayimg.com/images/g/qWkAAeSwQHtpw9b...,0.00,https://www.ebay.com/itm/178068331498?_skw=iPh...,178068331498
2,Apple iPhone X 64GB Space Gray (Unlocked) *473* G,75.99,$,Apple iPhone X,Buy It Now,"Jun 8, 2026",https://i.ebayimg.com/images/g/yKUAAeSweFVp610...,5.00,https://www.ebay.com/itm/198411150280?_skw=iPh...,198411150280
3,Apple iPhone X - 64 GB - Black- (Unlocked),55.00,$,Apple iPhone X,Auction,"Jun 7, 2026",https://i.ebayimg.com/images/g/kCQAAeSwOHBqGhC...,0.00,https://www.ebay.com/itm/267691024757?_skw=iPh...,267691024757
4,Apple iPhone X Silver 64GB MQCL2LL/A Factory U...,86.00,$,Apple iPhone X,Auction,"Jun 6, 2026",https://i.ebayimg.com/images/g/qQQAAeSwFLlqHix...,0.00,https://www.ebay.com/itm/800108759166?_skw=iPh...,800108759166
...,...,...,...,...,...,...,...,...,...,...
186,Apple iPhone X - 64GB - black (Unlocked),105.00,$,Apple iPhone X,Accepts Offers,"Apr 3, 2026",https://i.ebayimg.com/images/g/YZMAAeSwZLZpwwd...,9.00,https://www.ebay.com/itm/188204789976?_skw=iPh...,188204789976
187,Apple iPhone X 64GB Unlocked - Space Gray (No ...,89.99,$,Apple iPhone X,Accepts Offers,"Apr 3, 2026",https://i.ebayimg.com/images/g/o04AAeSw9hFpxfX...,8.06,https://www.ebay.com/itm/389804939802?_skw=iPh...,389804939802
188,Apple iPhone X 64GB Silver (Unlocked) A1865 (C...,119.99,$,Apple iPhone X,Buy It Now,"Apr 3, 2026",https://i.ebayimg.com/images/g/5VEAAeSwdDdpssF...,0.00,https://www.ebay.com/itm/317991800084?_skw=iPh...,317991800084
189,Apple iPhone X - 64 GB - Silver (Unlocked) - G...,80.00,$,Apple iPhone X,Auction,"Apr 3, 2026",https://i.ebayimg.com/images/g/Dn4AAeSwjbFpy~7...,6.80,https://www.ebay.com/itm/127783057568?_skw=iPh...,127783057568
190,Apple iPhone X UNLOCKED Any Carrier Silver 64G...,100.00,$,Apple iPhone X,Accepts Offers,"Mar 11, 2026",https://i.ebayimg.com/images/g/wgEAAeSwlNtpsYi...,0.00,https://www.ebay.com/itm/127733554493?_skw=iPh...,127733554493

In [250]:
from bs4 import BeautifulSoup

In [251]:
df.to_csv('Apple_iphone_selling_data.csv')

In [259]:

url = "https://the-web-scraping-api.p.rapidapi.com/browser"

querystring = {
    "url": "https://books.toscrape.com/",
    "country": "us",
    "headers": "{}",
    "method": "GET",
    "payload": "{}",
    "screenshot": "false",
    "fullScreenshot": "false"
}

headers = {
    "x-rapidapi-key": "50677ba5d5msh5e6bb409c408a3dp1292a7jsn8e64a441ed55",
    "x-rapidapi-host": "the-web-scraping-api.p.rapidapi.com",
    "Content-Type": "application/json"
}

response = requests.get(url, headers=headers, params=querystring)
html =response.text

In [260]:
data = json.loads(html)   

html_content = data["data"]

soup = BeautifulSoup(html_content, "html.parser")

books = soup.find_all("article", class_="product_pod")

print(len(books))

20

In [261]:
for book in books:
    title = book.h3.a["title"]

    price = book.find("p", class_="price_color").text

    rating = book.find("p")["class"][-1]

    print(title)
    print(price)
    print(rating)
    print("-" * 30)

A Light in the Attic
£51.77
Three
------------------------------
Tipping the Velvet
£53.74
One
------------------------------
Soumission
£50.10
One
------------------------------
Sharp Objects
£47.82
Four
------------------------------
Sapiens: A Brief History of Humankind
£54.23
Five
------------------------------
The Requiem Red
£22.65
One
------------------------------
The Dirty Little Secrets of Getting Your Dream Job
£33.34
Four
------------------------------
The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull
£17.93
Three
------------------------------
The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics
£22.60
Four
------------------------------
The Black Maria
£52.15
One
------------------------------
Starving Hearts (Triangular Trade Trilogy, #1)
£13.99
Two
------------------------------
Shakespeare's Sonnets
£20.66
Four
------------------------------
Set Me Free
£17.46
Five
------------------------------
Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)
£52.29
Five
------------------------------
Rip it Up and Start Again
£35.02
Five
------------------------------
Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991
£57.25
Three
------------------------------
Olio
£23.88
One
------------------------------
Mesaerion: The Best Science Fiction Stories 1800-1849
£37.59
One
------------------------------
Libertarianism for Beginners
£51.33
Two
------------------------------
It's Only the Himalayas
£45.17
Two
------------------------------

In [270]:
books_data = []

for book in books:
    title = book.h3.a["title"]
    price = book.find("p", class_="price_color").text
    rating = book.find("p")["class"][-1]

    books_data.append([title, price, rating])

df = pd.DataFrame(
    books_data,
    columns=["Title", "Price_euro", "Rating"]
)

In [271]:
df

                                                Title Price_euro Rating
0                                A Light in the Attic     £51.77  Three
1                                  Tipping the Velvet     £53.74    One
2                                          Soumission     £50.10    One
3                                       Sharp Objects     £47.82   Four
4               Sapiens: A Brief History of Humankind     £54.23   Five
5                                     The Requiem Red     £22.65    One
6   The Dirty Little Secrets of Getting Your Dream...     £33.34   Four
7   The Coming Woman: A Novel Based on the Life of...     £17.93  Three
8   The Boys in the Boat: Nine Americans and Their...     £22.60   Four
9                                     The Black Maria     £52.15    One
10     Starving Hearts (Triangular Trade Trilogy, #1)     £13.99    Two
11                              Shakespeare's Sonnets     £20.66   Four
12                                        Set Me Free     £17.46   Five
13  Scott Pilgrim's Precious Little Life (Scott Pi...     £52.29   Five
14                          Rip it Up and Start Again     £35.02   Five
15  Our Band Could Be Your Life: Scenes from the A...     £57.25  Three
16                                               Olio     £23.88    One
17  Mesaerion: The Best Science Fiction Stories 18...     £37.59    One
18                       Libertarianism for Beginners     £51.33    Two
19                            It's Only the Himalayas     £45.17    Two

In [272]:
df["Price_euro"] = df["Price_euro"].str.replace("£", "", regex=False).astype(float)
df

                                                Title  Price_euro Rating
0                                A Light in the Attic       51.77  Three
1                                  Tipping the Velvet       53.74    One
2                                          Soumission       50.10    One
3                                       Sharp Objects       47.82   Four
4               Sapiens: A Brief History of Humankind       54.23   Five
5                                     The Requiem Red       22.65    One
6   The Dirty Little Secrets of Getting Your Dream...       33.34   Four
7   The Coming Woman: A Novel Based on the Life of...       17.93  Three
8   The Boys in the Boat: Nine Americans and Their...       22.60   Four
9                                     The Black Maria       52.15    One
10     Starving Hearts (Triangular Trade Trilogy, #1)       13.99    Two
11                              Shakespeare's Sonnets       20.66   Four
12                                        Set Me Free       17.46   Five
13  Scott Pilgrim's Precious Little Life (Scott Pi...       52.29   Five
14                          Rip it Up and Start Again       35.02   Five
15  Our Band Could Be Your Life: Scenes from the A...       57.25  Three
16                                               Olio       23.88    One
17  Mesaerion: The Best Science Fiction Stories 18...       37.59    One
18                       Libertarianism for Beginners       51.33    Two
19                            It's Only the Himalayas       45.17    Two

In [274]:
df.to_csv('books_data.csv',index=False)